### ISSUE TITLE
Uncaught TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Christian-Thiem** [spark/particle-dev-cloud-variables#3]
[Enter steps to reproduce:]

1. Open a Cloud Variables Tab 
2. let it run for a while

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [particle-dev-cloud-variables](https://github.com/spark/particle-dev-cloud-variables) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'error' of undefined

```
At /Users/christianthiem/.atom/packages/particle-dev-cloud-variables/node_modules/spark/lib/spark.js:116

TypeError: Cannot read property 'error' of undefined
    at Spark.normalizeErr (/packages/particle-dev-cloud-variables/node_modules/spark/lib/spark.js:116:19)
    at /packages/particle-dev-cloud-variables/node_modules/spark/lib/spark.js:151:16)
    at Request.self.callback (/packages/particle-dev-cloud-variables/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/particle-dev-cloud-variables/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/particle-dev-cloud-variables/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
console-panel 0.3.0 
language-markdown 0.25.1 
language-particle 0.3.5 
markdown-preview-plus 2.4.10 
markdown-writer 2.7.2 
particle-dev 0.2.0 
particle-dev-cloud-functions 0.2.0 
particle-dev-cloud-variables 0.2.0 
particle-dev-profiles 0.2.3 
tool-bar 1.1.0 
```

**Comment by suda** [comment]
Hi Christian! Can you tell more about the issue? What was the device selected? What does `particle function list` CLI command show? How long were you waiting to see this error?
